### PR TITLE
Added nucleus

### PR DESCRIPTION
**Pull request by tacotopasu**
I'll leave the webring embed in https://nucleus.neocities.org/main
Not sure if it's allowed, let me know if not :3

### CODE REVIEW

**Comment by bucketfish** [comment]
ah, any reason you put yourself in that specific location? haha

**Comment by tacotopasu** [comment]
> ah, any reason you put yourself in that specific location? haha

Oh that was on accident haha, also my site is down right now, neocities hasn't told me why yet, my timing to join the webring was terrible sorry about that
I'll post a comment here again when it's back up

**Comment by bucketfish** [comment]
ooh, no worries then! i'll add you in, feel free to just add it to your website when it's back up ^^

**Comment by tacotopasu** [comment]
site is back up and the webring is in! thank you so much!

**Pull request merged**
