### PR TITLE
add lexiqqq

### PR DESCRIPTION
**Pull request by leximonzillo**

### CODE REVIEW

**Comment by bucketfish** [comment]
welcome!!!

**Comment by leximonzillo** [comment]
thanks ^^

Il giorno ven 5 gen 2024 alle ore 08:21 bucketfish ***@***.***>
ha scritto:

**Comment by bucketfish** [comment]
hey @leximonzillo! i can't find the webring embed on your site — am i missing something? let me know if you need help putting it up (or if you'd like to drop out of the webring :o)

**Comment by leximonzillo** [comment]
hi ^^ you can find it here:
https://www.lexiqqq.com/pages/recommended.php

Il giorno sab 10 feb 2024 alle 06:39 bucketfish ***@***.***>
ha scritto:

**Pull request merged**
