### PR TITLE
Update webring.json

### PR DESCRIPTION
**Pull request by computerguts**
help i dont know how github works?? is a commit change the same as a pull request im completely lost sorry if this breaks your code somehow </3

ok i think im in the pull request thing now hoping this works

### CODE REVIEW

**Comment by eightheve** [comment]
a commit means adding a change to a branch (I.E. editing your own personal version of a file), and a pull request is a request to merge your branch of the repository, your personal version that you can edit, with the upstream branch, the one that you cannot (which is this one). Also your website is very cool and I am excited for u to join but I can't merge the request right now because there isn't a comma on the end of the line before urs so it would mess up the json but once thats fixed (which I think I can also do for you if you want?) It can be merged no problem

**Comment by eightheve** [comment]
all good now :) thank you!! and welcome in :3

**Comment by computerguts** [comment]
WOOOO YEEAH

**Comment by eightheve** [comment]
also u should join tha discord anyways because i like your site and i want to talk to you :yum:

**Pull request merged**
