### PR TITLE
.

### PR DESCRIPTION
**Pull request by tiagozip**
deleted!

### CODE REVIEW

**Comment by eightheve** [comment]
you need to remove the trailing comma and then it can be merged

**Comment by tiagorangel2011** [comment]
done :) @eightheve

**Comment by eightheve** [comment]
thank you and welcome :)

**Comment by tiagorangel2011** [comment]
thank you too! setting up nav links soon

**Comment by tiagorangel2011** [comment]
btw is there a bucket webring antipixel?

**Pull request merged**
