### PR TITLE
Add andrew

### PR DESCRIPTION
**Pull request by therealandreww**

### CODE REVIEW

**Comment by bucketfish** [comment]
SO SORRY ABOUT BEING LATE!!! i was too busy then i forgot about this 😭 welcome to the webring!!!

**Comment by therealandreww** [comment]
Sorry- could you change the URL to `https://andrewslair.org`?

**Comment by bucketfish** [comment]
done! :)

**Comment by bucketfish** [comment]
hey @therealandreww, i can't find the webring link on your website — am i missing something? haha lmk if you need help putting it up!

**Comment by therealandreww** [comment]
oops, I forgot about that 😅 I'm away from home right now so I'll make sure to update my site when I come back. Thanks for letting me know :)

**Comment by therealandreww** [comment]
fixed :D

**Pull request merged**
